### ISSUE TITLE
Bug: compilation error

### ISSUE THREAD

**Issue by swervx** [AnchyDev/TalentProfiles#1]
### Current Behaviour

Hello,

can you help me ?

The mod does not compile.
![Capture d'écran 2024-04-04 181416](https://github.com/AnchyDev/TalentProfiles/assets/101983666/1b3f5291-935a-4813-9d83-c2958b341385)

### Expected Behaviour

should be able to compile

### Steps to reproduce the problem

Does not compile

### AC rev. hash/commit

None

### Operating system

Windows 11 x64

**Comment by AnchyDev** [comment]
This is a test project and not really designed to be used yet which is why I did not attach the azerothcore-module topic to it.
